# SPDX-FileCopyrightText: 2025 igniter_css contributors <https://github.com/ash-project/igniter_css/graphs/contributors>
#
# SPDX-License-Identifier: MIT

name: CI
on:
  push:
    tags:
      - "v*"
    branches: [main, 'test/**']
  pull_request:
    branches: [main]
  workflow_call:
jobs:
  ash-ci:
    strategy:
      fail-fast: false
      matrix:
        include:
          - elixir-version: "1.17.0-otp-26"
            erlang-version: "26.0"
            primary: false
          - elixir-version: "default"
            erlang-version: "default"
            primary: true
    uses: shahryarjb/ash/.github/workflows/ash-ci.yml@ci/parameterise-rustler-precompiled-build
    with:
      spark-formatter: false
      spark-cheat-sheets: false
      sobelow: false
      elixir-version: ${{ matrix.elixir-version }}
      erlang-version: ${{ matrix.erlang-version }}
      igniter-upgrade: false
      rustler-precompiled-module: IgniterCss.Native
      rust-crate-dir: native/igniter_css
      publish-docs: ${{ matrix.primary }}
      reuse: true
      release: false
    secrets:
      HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
